### ISSUE TITLE
Change the namespace dapr-shared runs in?

### ISSUE THREAD

**Issue by joshuajohananorthos** [dapr/dapr-shared#51]
I tried to install the helm chart using a different namespace. Everything installed, but it was not able to come up because it could not find the configmap.

`'Error: configmap "dapr-shared-cm" not found'`

I investigated and found that the configmap is in the default namespace and not with the deployment so it cannot come up.

**Comment by salaboy** [comment]
@joshuajohananorthos thanks for reporting this.. let's get this one fixed.. it should be an easy fix.. do you want to submit a PR?
